version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - skip-changelog
      - dependency
    versioning-strategy: increase
    rebase-strategy: disabled
    ignore:
      - dependency-name: "prettier*"
      - dependency-name: "chalk"
      - dependency-name: "jest"
      - dependency-name: "*eslint*"
